spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/BookMySpace
      username: root
      password: sellvaSS@01
  jpa:
    hibernate:
      ddl-auto: update
    mysql:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8082
